# Production environment configuration
aws_accounts:
  management: "396913723725"
  dev: "688567306703"
  staging: "400205986141"
  prod: "825765407025"

budgets:
  organization:
    limit: 50  # Higher limit for production
    currency: "USD"
  accounts:
    dev: 10
    staging: 15
    prod: 25

notifications:
  email: "bsmorris1+aws@gmail.com"
  thresholds:
    warning: 80
    critical: 90  # Earlier warning for production

cost_tags:
  - Environment
  - Project
  - Owner
  - CostCenter