---
- name: Generate Terraform files from templates
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  
  tasks:
    - name: Generate cost-management.tf from template
      template:
        src: ../templates/cost-management.tf.j2
        dest: ../../terraform/cost-management.tf
        backup: yes
      
    - name: Format generated Terraform file
      shell: terraform fmt ../../terraform/cost-management.tf
      
    - name: Display generated file location
      debug:
        msg: "Generated terraform/cost-management.tf with current configuration"